//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_ir
 * @{
 */

/** Current ibase_ir. */
#define IBASE_IR    (&OLSR->ibase_ir)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_ir_iter() \
    ((tuple_ir_t*)(tuple_ir_t*)IBASE_IR->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_ir_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_IR))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_ir_iter_next(iter) \
    ((tuple_ir_t*)(tuple_ir_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_ir_iter_end()    ((tuple_ir_t*)IBASE_IR)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_IR(p)                     \
    for (tuple_ir_t* p = ibase_ir_iter(); \
         !ibase_ir_iter_is_end(p);        \
         p = ibase_ir_iter_next(p))

/** Sets timeout to the tuple.
 *
 * @param tuple
 * @param t
 */
#define tuple_ir_set_timeout(tuple, t)             \
    tuple_time_set_timeout((tuple_time_t*)(tuple), \
        &(OLSR)->ibase_ir_time_list, (t))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Clears the change flag.
 */
#define ibase_ir_clear_change_flag() \
    do { IBASE_IR->change = false; } \
    while (0)

/** Checks whether the ibase has been changed.
 */
#define ibase_ir_is_changed() \
    ((nu_bool_t)(IBASE_IR->change))

/** Sets the change flag of the ibase.
 */
#define ibase_ir_change()           \
    do { IBASE_IR->change = true; } \
    while (0)

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_ir_is_empty()    ((void*)(IBASE_IR) == (void*)IBASE_IR->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_ir_size()        ((IBASE_IR)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_ir_head()        ((ibase_ir_is_empty()) ? NULL : (IBASE_IR)->next)

/** @} */

}//namespace// //ScenSim-Port://
