//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_ta
 * @{
 */

/** Current ibase_ta. */
#define IBASE_TA    (&OLSR->ibase_ta)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_ta_iter() \
    ((tuple_ta_t*)(tuple_ta_t*)IBASE_TA->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_ta_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_TA))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_ta_iter_next(iter) \
    ((tuple_ta_t*)(tuple_ta_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_ta_iter_end()    ((tuple_ta_t*)IBASE_TA)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_TA(p)                     \
    for (tuple_ta_t* p = ibase_ta_iter(); \
         !ibase_ta_iter_is_end(p);        \
         p = ibase_ta_iter_next(p))

/** Sets timeout to the tuple.
 *
 * @param tuple
 * @param t
 */
#define tuple_ta_set_timeout(tuple, t)             \
    tuple_time_set_timeout((tuple_time_t*)(tuple), \
        &(OLSR)->ibase_ta_time_list, (t))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Clears the change flag.
 */
#define ibase_ta_clear_change_flag() \
    do { IBASE_TA->change = false; } \
    while (0)

/** Checks whether the ibase has been changed.
 */
#define ibase_ta_is_changed() \
    ((nu_bool_t)(IBASE_TA->change))

/** Sets the change flag of the ibase.
 */
#define ibase_ta_change()           \
    do { IBASE_TA->change = true; } \
    while (0)

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_ta_is_empty()    ((void*)(IBASE_TA) == (void*)IBASE_TA->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_ta_size()        ((IBASE_TA)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_ta_head()        ((ibase_ta_is_empty()) ? NULL : (IBASE_TA)->next)

/** @} */

}//namespace// //ScenSim-Port://
