//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_n
 * @{
 */

/** Current ibase_n. */
#define IBASE_N    (&OLSR->ibase_n)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_n_iter() \
    ((tuple_n_t*)(tuple_n_t*)IBASE_N->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_n_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_N))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_n_iter_next(iter) \
    ((tuple_n_t*)(tuple_n_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_n_iter_end()    ((tuple_n_t*)IBASE_N)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_N(p)                    \
    for (tuple_n_t* p = ibase_n_iter(); \
         !ibase_n_iter_is_end(p);       \
         p = ibase_n_iter_next(p))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Clears the change flag.
 */
#define ibase_n_clear_change_flag() \
    do { IBASE_N->change = false; } \
    while (0)

/** Checks whether the ibase has been changed.
 */
#define ibase_n_is_changed() \
    ((nu_bool_t)(IBASE_N->change))

/** Sets the change flag of the ibase.
 */
#define ibase_n_change()           \
    do { IBASE_N->change = true; } \
    while (0)

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_n_is_empty()    ((void*)(IBASE_N) == (void*)IBASE_N->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_n_size()        ((IBASE_N)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_n_head()        ((ibase_n_is_empty()) ? NULL : (IBASE_N)->next)

/** @} */

}//namespace// //ScenSim-Port://
