//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_ar
 * @{
 */

/** Current ibase_ar. */
#define IBASE_AR    (&OLSR->ibase_ar)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_ar_iter() \
    ((tuple_ar_t*)(tuple_ar_t*)IBASE_AR->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_ar_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_AR))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_ar_iter_next(iter) \
    ((tuple_ar_t*)(tuple_ar_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_ar_iter_end()    ((tuple_ar_t*)IBASE_AR)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_AR(p)                     \
    for (tuple_ar_t* p = ibase_ar_iter(); \
         !ibase_ar_iter_is_end(p);        \
         p = ibase_ar_iter_next(p))

/** Sets timeout to the tuple.
 *
 * @param tuple
 * @param t
 */
#define tuple_ar_set_timeout(tuple, t)             \
    tuple_time_set_timeout((tuple_time_t*)(tuple), \
        &(OLSR)->ibase_ar_time_list, (t))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_ar_is_empty()    ((void*)(IBASE_AR) == (void*)IBASE_AR->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_ar_size()        ((IBASE_AR)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_ar_head()        ((ibase_ar_is_empty()) ? NULL : (IBASE_AR)->next)

/** @} */

}//namespace// //ScenSim-Port://
