//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_tr
 * @{
 */

/** Current ibase_tr. */
#define IBASE_TR    (&OLSR->ibase_tr)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_tr_iter() \
    ((tuple_tr_t*)(tuple_tr_t*)IBASE_TR->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_tr_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_TR))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_tr_iter_next(iter) \
    ((tuple_tr_t*)(tuple_tr_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_tr_iter_end()    ((tuple_tr_t*)IBASE_TR)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_TR(p)                     \
    for (tuple_tr_t* p = ibase_tr_iter(); \
         !ibase_tr_iter_is_end(p);        \
         p = ibase_tr_iter_next(p))

/** Sets timeout to the tuple.
 *
 * @param tuple
 * @param t
 */
#define tuple_tr_set_timeout(tuple, t)             \
    tuple_time_set_timeout((tuple_time_t*)(tuple), \
        &(OLSR)->ibase_tr_time_list, (t))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Clears the change flag.
 */
#define ibase_tr_clear_change_flag() \
    do { IBASE_TR->change = false; } \
    while (0)

/** Checks whether the ibase has been changed.
 */
#define ibase_tr_is_changed() \
    ((nu_bool_t)(IBASE_TR->change))

/** Sets the change flag of the ibase.
 */
#define ibase_tr_change()           \
    do { IBASE_TR->change = true; } \
    while (0)

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_tr_is_empty()    ((void*)(IBASE_TR) == (void*)IBASE_TR->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_tr_size()        ((IBASE_TR)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_tr_head()        ((ibase_tr_is_empty()) ? NULL : (IBASE_TR)->next)

/** @} */

}//namespace// //ScenSim-Port://
