//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_i
 * @{
 */

/** Current ibase_i. */
#define IBASE_I    (&OLSR->ibase_i)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_i_iter() \
    ((tuple_i_t*)(tuple_i_t*)IBASE_I->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_i_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_I))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_i_iter_next(iter) \
    ((tuple_i_t*)(tuple_i_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_i_iter_end()    ((tuple_i_t*)IBASE_I)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_I(p)                    \
    for (tuple_i_t* p = ibase_i_iter(); \
         !ibase_i_iter_is_end(p);       \
         p = ibase_i_iter_next(p))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_i_is_empty()    ((void*)(IBASE_I) == (void*)IBASE_I->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_i_size()        ((IBASE_I)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_i_head()        ((ibase_i_is_empty()) ? NULL : (IBASE_I)->next)

/** @} */

}//namespace// //ScenSim-Port://
