//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_r
 * @{
 */

/** Current ibase_r. */
#define IBASE_R    (&OLSR->ibase_r)

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator.
 *
 * @return iterator which points the first tuple
 */
#define  ibase_r_iter() \
    ((tuple_r_t*)(tuple_r_t*)IBASE_R->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_r_iter_is_end(iter) \
    ((nu_bool_t)((void*)(iter) == (void*)IBASE_R))

/** Gets next iterator.
 *
 * @param iter
 * @return iterator which points the next tuple
 */
#define ibase_r_iter_next(iter) \
    ((tuple_r_t*)(tuple_r_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @return iterator which points the end of the ibase
 */
#define ibase_r_iter_end()    ((tuple_r_t*)IBASE_R)

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 */
#define FOREACH_R(p)                    \
    for (tuple_r_t* p = ibase_r_iter(); \
         !ibase_r_iter_is_end(p);       \
         p = ibase_r_iter_next(p))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Clears the change flag.
 */
#define ibase_r_clear_change_flag() \
    do { IBASE_R->change = false; } \
    while (0)

/** Checks whether the ibase has been changed.
 */
#define ibase_r_is_changed() \
    ((nu_bool_t)(IBASE_R->change))

/** Sets the change flag of the ibase.
 */
#define ibase_r_change()           \
    do { IBASE_R->change = true; } \
    while (0)

/** Checks whether the ibase is empty.
 *
 * @return true if the ibase is empty
 */
#define ibase_r_is_empty()    ((void*)(IBASE_R) == (void*)IBASE_R->next)

/** Gets the size of the ibase.
 *
 * @return the size of the ibase
 */
#define ibase_r_size()        ((IBASE_R)->n)

/** Gets the top tuple of the ibase.
 *
 * @return the top tuple of the ibase
 */
#define ibase_r_head()        ((ibase_r_is_empty()) ? NULL : (IBASE_R)->next)

/** @} */

}//namespace// //ScenSim-Port://
