//
// This file is automatically generated from tempalte/ibase.h
//

namespace NuOLSRv2Port { //ScenSim-Port://

/************************************************************//**
 * @addtogroup ibase_lt
 * @{
 */

////////////////////////////////////////////////////////////////
//
// Iterator
//

/** Gets iterator of ibase.
 *
 * @param ibase
 * @return iterator which points the first tuple
 */
#define ibase_lt_iter(ibase) \
    ((tuple_lt_t*)(tuple_lt_t*)(ibase)->next)

/** Checks whether iterator points end of the ibase.
 *
 * @param ibase
 * @param iter
 * @return true if iter points to the end of ibase
 */
#define ibase_lt_iter_is_end(iter, ibase) \
    ((nu_bool_t)((void*)iter == (void*)(ibase)))

/** Gets next iterator.
 *
 * @param ibase
 * @param iter
 * @return iterator which points the next iter
 */
#define ibase_lt_iter_next(iter, ibase) \
    ((tuple_lt_t*)(tuple_lt_t*)(iter)->next)

/** Gets the pointer which points end of the ibase.
 *
 * @param ibase
 * @return iterator which points the end of the ibase
 */
#define ibase_lt_iter_end(ibase)    ((tuple_lt_t*)(ibase))

/** Traverses ibase.
 *
 * @param p
 */

/** Traverses the ibase.
 *
 * @param p
 * @param ibase
 */
#define FOREACH_LT(p, ibase)                   \
    for (tuple_lt_t* p = ibase_lt_iter(ibase); \
         !ibase_lt_iter_is_end(p, ibase);      \
         p = ibase_lt_iter_next(p, ibase))

////////////////////////////////////////////////////////////////
//
// Information Base
//

/** Checks whether the ibase is empty.
 *
 * @param ibase
 * @return true if the ibase is empty
 */
#define ibase_lt_is_empty(ibase)    ((void*)(ibase) == (void*)(ibase)->next)

/** Gets the size of the ibase.
 *
 * @param ibase
 * @return the size of the ibase
 */
#define ibase_lt_size(ibase)        ((ibase)->n)

/** Gets the top tuple of the ibase.
 *
 * @param ibase
 * @return the top tuple of the ibase
 */
#define ibase_lt_head(ibase)        ((ibase_lt_is_empty(ibase)) ? NULL : (ibase)->next)

/** @} */

}//namespace// //ScenSim-Port://
